version: '3.8'
services:
  postgres-auth:
    image: postgres:15-alpine
    container_name: careuce-postgres-auth
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-auth_db}
    ports:
      - '5433:5432'
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres-triage:
    image: postgres:15-alpine
    container_name: careuce-postgres-triage
    environment:
      POSTGRES_USER: ${TRIAGE_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${TRIAGE_DB_PASSWORD:-root}
      POSTGRES_DB: ${TRIAGE_DB_NAME:-triage_db}
    ports:
      - '5434:5432' # Usamos el 5434 en tu PC para no chocar con el 5433 de auth
    volumes:
      - postgres_triage_data:/var/lib/postgresql/data

  # fIXED
  kafka:
    image: apache/kafka:3.8.0
    ports:
      - '9092:9092'
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

volumes:
  postgres_auth_data:
  postgres_triage_data:
