version: '3.8'

services:
  # --- BASES DE DATOS RELACIONALES ---
  auth-db:
    image: postgres:15-alpine
    container_name: careuce-auth-db-qa
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-auth_db}
    networks:
      - careuce-qa-network

  triage-db:
    image: postgres:15-alpine
    container_name: careuce-triage-db-qa
    restart: always
    environment:
      POSTGRES_USER: ${TRIAGE_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${TRIAGE_DB_PASSWORD:-root}
      POSTGRES_DB: ${TRIAGE_DB_NAME:-triage_db}
    networks:
      - careuce-qa-network

  # 🔥 NUEVO: BASE DE DATOS DOCUMENTAL
  mongodb:
    image: mongo:6.0
    container_name: careuce-mongodb-qa
    restart: always
    ports:
      - '27017:27017'
    networks:
      - careuce-qa-network

  # 🔥 NUEVO: SISTEMA NERVIOSO (KAFKA EN MODO KRAFT)
  kafka:
    image: apache/kafka:3.8.0
    container_name: careuce-kafka-qa
    restart: always
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_TOPICS_AUTOMATIC_CREATION_ENABLE=true
    networks:
      - careuce-qa-network

  # --- EL API GATEWAY ---
  api-gateway:
    image: nginx:alpine
    container_name: careuce-api-gateway-qa
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - triage-service
    networks:
      - careuce-qa-network

  # --- MICROSERVICIOS ---
  auth-service:
    image: ${DOCKER_USERNAME}/careuce-auth:qa
    container_name: careuce-auth-service-qa
    restart: always
    depends_on:
      - auth-db
    env_file:
      - .env
    networks:
      - careuce-qa-network

  triage-service:
    image: ${DOCKER_USERNAME}/careuce-triage:qa
    container_name: careuce-triage-service-qa
    restart: always
    depends_on:
      - triage-db
      - kafka # 🔥 Triage ahora debe esperar a que Kafka despierte
    environment:
      - KAFKA_BROKER=kafka:9092 # Inyectamos la URL interna de Kafka
    env_file:
      - .env
    networks:
      - careuce-qa-network

  # 🔥 NUEVO: MICROSERVICIO CONSUMIDOR
  clinical-service:
    image: ${DOCKER_USERNAME}/careuce-clinical:qa
    container_name: careuce-clinical-service-qa
    restart: always
    depends_on:
      - kafka
      - mongodb
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGO_URI=mongodb://mongodb:27017/clinical_db
    env_file:
      - .env
    networks:
      - careuce-qa-network

networks:
  careuce-qa-network:
    driver: bridge
