version: '3.8'

services:
  # 1. Contenedor de Base de Datos para Auth Service
  auth-db:
    image: postgres:15-alpine
    container_name: careuce-auth-db-qa
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_NAME:-auth_db}
    networks:
      - careuce-qa-network

  # 🔥 NUEVO: Contenedor de Base de Datos para Triage Service
  triage-db:
    image: postgres:15-alpine
    container_name: careuce-triage-db-qa
    restart: always
    environment:
      POSTGRES_USER: ${TRIAGE_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${TRIAGE_DB_PASSWORD:-root}
      POSTGRES_DB: ${TRIAGE_DB_NAME:-triage_db}
    networks:
      - careuce-qa-network

  # 2. EL API GATEWAY (La nueva puerta de enlace)
  api-gateway:
    image: nginx:alpine
    container_name: careuce-api-gateway-qa
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - triage-service # 🔥 Nginx ahora espera a ambos
    networks:
      - careuce-qa-network

  # 3. Microservicio de Autenticación
  auth-service:
    image: ${DOCKER_USERNAME}/careuce-auth:qa
    container_name: careuce-auth-service-qa
    restart: always
    depends_on:
      - auth-db
    env_file:
      - .env
    networks:
      - careuce-qa-network

  # 🔥 NUEVO: Microservicio de Triage
  triage-service:
    image: ${DOCKER_USERNAME}/careuce-triage:qa
    container_name: careuce-triage-service-qa
    restart: always
    depends_on:
      - triage-db
    env_file:
      - .env
    networks:
      - careuce-qa-network

networks:
  careuce-qa-network:
    driver: bridge
