# Identificador único de tu proyecto
sonar.projectKey=careuce-monorepo

# Le dice al escáner que busque código desde la raíz
sonar.sources=.

# Carpetas que NO quieres analizar (librerías, entornos virtuales y compilados)
sonar.exclusions=**/node_modules/**,**/venv/**,**/.next/**,**/dist/**,**/build/**