events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Opcional: Una ruta raíz para que el Load Balancer verifique que el Gateway está vivo
        location / {
            return 200 'CareUCE API Gateway is running!';
            add_header Content-Type text/plain;
        }

        #  ARREGLO: Enrutamiento Transparente (Sin barras al final)
        location /api/auth {
            proxy_pass http://auth-service:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        #  NUEVO: Enrutamiento para Triage Service
        location /api/triage/ {
            proxy_pass http://triage-service:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Aquí agregaremos las rutas para Triage, Clinical, etc., en el futuro.
    }
}